### ISSUE TITLE
segment violation connectGrpcServer

### ISSUE THREAD

**Issue by HoganEdwardChu** [pinpoint-apm/pinpoint-go-agent#74]
Can't figure out what happens the problem.
Problem state is below

signal SIGSEGV: segmentation violation code happen
version
google.golang.org/grpc v1.49.0 // indirect
google.golang.org/protobuf v1.28.1 // indirect

Using plugin echov4 and sarama

```cpp
2023-05-03T18:35:13.121402971+09:00 unexpected fault address 0x0
2023-05-03T18:35:13.121430626+09:00 fatal error: fault
2023-05-03T18:35:13.123441480+09:00 [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4d465c]
2023-05-03T18:35:13.123446219+09:00
2023-05-03T18:35:13.123448622+09:00 goroutine 43 [running]:
2023-05-03T18:35:13.123723992+09:00 runtime.throw({0x13a46d1?, 0x405454?})
2023-05-03T18:35:13.123735544+09:00 	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc004131608 sp=0xc0041315d8 pc=0x438dfd
2023-05-03T18:35:13.123762071+09:00 runtime.sigpanic()
2023-05-03T18:35:13.123777285+09:00 	/usr/local/go/src/runtime/signal_unix.go:851 +0x28a fp=0xc004131668 sp=0xc004131608 pc=0x44f0aa
2023-05-03T18:35:13.123791830+09:00 reflect.packEface({0x13154a0?, 0x7473657571373939?, 0x1387020?})
2023-05-03T18:35:13.123794537+09:00 	/usr/local/go/src/reflect/value.go:132 +0x7c fp=0xc0041316b8 sp=0xc004131668 pc=0x4d465c
2023-05-03T18:35:13.123797002+09:00 reflect.valueInterface({0x13154a0?, 0x7473657571373939?, 0x12e9be0?}, 0x20?)
2023-05-03T18:35:13.123798890+09:00 	/usr/local/go/src/reflect/value.go:1510 +0xbb fp=0xc0041316f8 sp=0xc0041316b8 pc=0x4daadb
2023-05-03T18:35:13.123801429+09:00 reflect.Value.Interface(...)
2023-05-03T18:35:13.123805485+09:00 	/usr/local/go/src/reflect/value.go:1480
2023-05-03T18:35:13.123813557+09:00 google.golang.org/protobuf/internal/impl.(*messageConverter).PBValueOf(0xc0002f3c80, {0x13154a0?, 0x7473657571373939?, 0xc00362d000?})
2023-05-03T18:35:13.123817229+09:00 	/opt/app-root/src/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:433 +0x16a fp=0xc0041317a0 sp=0xc0041316f8 pc=0x8381ca
2023-05-03T18:35:13.123820012+09:00 google.golang.org/protobuf/internal/impl.(*listReflect).Get(0xc003f00d20, 0x155bdc0?)
2023-05-03T18:35:13.123822442+09:00 	/opt/app-root/src/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert_list.go:114 +0x5d fp=0xc0041317d8 sp=0xc0041317a0 pc=0x83a01d
2023-05-03T18:35:13.123831604+09:00 github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc003f00b70, {0x1555bd8, 0xc003a23750})
2023-05-03T18:35:13.123837338+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:287 +0x61e fp=0xc004131968 sp=0xc0041317d8 pc=0x86a73e
2023-05-03T18:35:13.123860612+09:00 github.com/golang/protobuf/proto.(*textWriter).writeSingularValue(0xc003f00b70, {{}, 0x1361800?, 0xc003a23750?, 0xc004131a01?}, {0x155bdc0, 0xc000d56b40})
2023-05-03T18:35:13.123883701+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:390 +0x5b6 fp=0xc004131a38 sp=0xc004131968 pc=0x86bc76
2023-05-03T18:35:13.123889149+09:00 github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc003f00b70, {0x1555bd8, 0xc003a23500})
2023-05-03T18:35:13.123891406+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:288 +0x645 fp=0xc004131bc8 sp=0xc004131a38 pc=0x86a765
2023-05-03T18:35:13.123952283+09:00 github.com/golang/protobuf/proto.(*textWriter).writeSingularValue(0xc003f00b70, {{}, 0x1361800?, 0xc003a23500?, 0x7fe24d81b108?}, {0x155bdc0, 0xc00001ad20})
2023-05-03T18:35:13.124005711+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:390 +0x5b6 fp=0xc004131c98 sp=0xc004131bc8 pc=0x86bc76
2023-05-03T18:35:13.124019923+09:00 github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc003f00b70, {0x1555bd8, 0xc003a234f0})
2023-05-03T18:35:13.124062417+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:341 +0x4a5 fp=0xc004131e28 sp=0xc004131c98 pc=0x86a5c5
2023-05-03T18:35:13.124069826+09:00 github.com/golang/protobuf/proto.(*TextMarshaler).marshal(0x1dcb680, {0x15497d0?, 0xc003f00ae0})
2023-05-03T18:35:13.124076007+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:86 +0x12f fp=0xc004131e80 sp=0xc004131e28 pc=0x868e0f
2023-05-03T18:35:13.124082813+09:00 github.com/golang/protobuf/proto.(*TextMarshaler).Text(...)
2023-05-03T18:35:13.124089128+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:44
2023-05-03T18:35:13.124095006+09:00 github.com/golang/protobuf/proto.CompactTextString(...)
2023-05-03T18:35:13.124118289+09:00 	/opt/app-root/src/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:106
2023-05-03T18:35:13.124128320+09:00 github.com/pinpoint-apm/pinpoint-go-agent/protobuf.(*PSpanMessage).String(...)
2023-05-03T18:35:13.124135256+09:00 	/opt/app-root/src/go/pkg/mod/github.com/pinpoint-apm/pinpoint-go-agent@v1.3.1/protobuf/Span.pb.go:34
2023-05-03T18:35:13.124141214+09:00 github.com/pinpoint-apm/pinpoint-go-agent.(*spanStream).sendSpan(0xc001594930, 0xc002ac1c80?)
2023-05-03T18:35:13.124147329+09:00 	/opt/app-root/src/go/pkg/mod/github.com/pinpoint-apm/pinpoint-go-agent@v1.3.1/grpc.go:577 +0x89 fp=0xc004131f00 sp=0xc004131e80 pc=0xa6b369
2023-05-03T18:35:13.124153319+09:00 github.com/pinpoint-apm/pinpoint-go-agent.(*agent).sendSpanWorker(0xc00027e5a0)
2023-05-03T18:35:13.124159498+09:00 	/opt/app-root/src/go/pkg/mod/github.com/pinpoint-apm/pinpoint-go-agent@v1.3.1/agent.go:333 +0x1fe fp=0xc004131fc8 sp=0xc004131f00 pc=0xa5ebfe
2023-05-03T18:35:13.124165706+09:00 github.com/pinpoint-apm/pinpoint-go-agent.(*agent).connectGrpcServer.func2()
2023-05-03T18:35:13.124171948+09:00 	/opt/app-root/src/go/pkg/mod/github.com/pinpoint-apm/pinpoint-go-agent@v1.3.1/agent.go:188 +0x26 fp=0xc004131fe0 sp=0xc004131fc8 pc=0xa5dfc6
2023-05-03T18:35:13.124177829+09:00 runtime.goexit()
2023-05-03T18:35:13.124201292+09:00 	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc004131fe8 sp=0xc004131fe0 pc=0x46b7e1
2023-05-03T18:35:13.124212559+09:00 created by github.com/pinpoint-apm/pinpoint-go-agent.(*agent).connectGrpcServer
2023-05-03T18:35:13.124219688+09:00 	/opt/app-root/src/go/pkg/mod/github.com/pinpoint-apm/pinpoint-go-agent@v1.3.1/agent.go:188 +0x1aa
```

**Comment by HoganEdwardChu** [comment]
Solved The Problem
Thank you @dwkang
